version: 0.2
cache:
  paths:
    - node_modules/**/*
phases:
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - export NODE_OPTIONS=--max_old_space_size=2048
      - npx ng build --configuration=production --source-map=false
  post_build:
    commands:
      - cp appspec.yml dist/template/browser/
      - cp -r scripts dist/template/browser/
artifacts:
  base-directory: dist/template/browser
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'